pull_request_rules:
  - name: automatic merge for Dependabot pull requests
    conditions:
      - author~=^dependabot(|-preview)\[bot\]$
      - check-success=test
      - check-success=terraform
      - title~=^chore: bump [^\s]+ from ([1-9][\d]*)\..+ to \1\.
    actions:
      merge:
        method: merge
