version: '3'
services:
  postgres:
    image: postgres:13
    restart: always
    ports:
      - "$TYPEORM_PORT:5432"
    environment:
      POSTGRES_USER: $TYPEORM_USERNAME
      POSTGRES_DB: $TYPEORM_DATABASE
      POSTGRES_PASSWORD: $TYPEORM_PASSWORD
    volumes:
      - pg_data:/var/lib/postgresql/data/

  api:
    build: .
    ports:
      - "3000:$API_SERVER_PORT"
    depends_on:
      - postgres

volumes:
  pg_data:
    driver: local
