version: '3'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    ports:
      - $TYPEORM_PORT:3306
    environment:
      TZ: Asia/Tokyo
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: $TYPEORM_DATABASE
      MYSQL_USER: $TYPEORM_USERNAME
      MYSQL_PASSWORD: $TYPEORM_PASSWORD
    volumes:
      - mysql_data:/var/lib/mysql
      - ./my.cnf:/etc/mysql/conf.d/my.cnf

  api:
    build: .
    container_name: api
    environment:
      TZ: Asia/Tokyo
    ports:
      - 3000:$SERVER_PORT
    working_dir: /app
    depends_on:
      - mysql

volumes:
  mysql_data:
    driver: local
